theme: jekyll-theme-minimal
logo: https://bioboot.github.io/bggn213_W20/assets/img/logo.png
title: Gene Drive Mutation Accumulation Experiment \nKryazhimskiy Lab \nUniversity of California, San Diego
